import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import warnings
warnings.filterwarnings('ignore')

# --- CONFIGURATION ---
MODEL_DIR = 'models'

print("1. Loading Pre-Trained Models and Held-Out Test Sets...")
with open(f'{MODEL_DIR}/training_features.json', 'r') as f:
    training_features = json.load(f)

model_coast = XGBRegressor()
model_coast.load_model(f'{MODEL_DIR}/coast_model.json')
model_river = XGBRegressor()
model_river.load_model(f'{MODEL_DIR}/river_model.json')

# These CSVs contain ONLY transects that were never seen during training
# (generated by train_model.py via the segment_id group split)
df_coast_test = pd.read_csv(f'{MODEL_DIR}/test_coast.csv')
df_river_test = pd.read_csv(f'{MODEL_DIR}/test_river.csv')

df_coast_test['date'] = pd.to_datetime(df_coast_test['date'])
df_river_test['date'] = pd.to_datetime(df_river_test['date'])

# Re-apply categorical dtypes (lost in the CSV round-trip)
for d in (df_coast_test, df_river_test):
    d['site_name'] = d['site_name'].astype('category')
    d['satellite'] = d['satellite'].astype('category')

target = 'cross_distance_m'

print(f"   Coast test set : {df_coast_test['segment_id'].nunique()} transects, {len(df_coast_test)} rows")
print(f"   River test set : {df_river_test['segment_id'].nunique()} transects, {len(df_river_test)} rows")

print("\n2. Running Predictions on Unseen Transects...")
df_coast_test['pred_position'] = model_coast.predict(df_coast_test[training_features])
df_river_test['pred_position'] = model_river.predict(df_river_test[training_features])

df_eval = pd.concat([df_coast_test, df_river_test], ignore_index=True)
mask_coast = df_eval['in_river_zone'] == 0
mask_river = df_eval['in_river_zone'] == 1

print("\n3. Calculating Performance Metrics (Held-Out Transects Only)...")

def print_metrics(name, y_true, y_pred):
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)
    print(f"=== {name} ===")
    print(f"  RMSE : {rmse:.2f} m")
    print(f"  MAE  : {mae:.2f} m (Average error margin on absolute position)")
    print(f"  R2   : {r2:.3f}\n")

print_metrics("GLOBAL PERFORMANCE (unseen transects)", df_eval[target], df_eval['pred_position'])
if mask_coast.sum() > 0:
    print_metrics("Coastal (unseen transects)", df_eval.loc[mask_coast, target], df_eval.loc[mask_coast, 'pred_position'])
if mask_river.sum() > 0:
    print_metrics("River (unseen transects)", df_eval.loc[mask_river, target], df_eval.loc[mask_river, 'pred_position'])

print("4. Generating Evaluation Plot...")
plt.figure(figsize=(10, 8))
plt.scatter(df_eval.loc[mask_coast, target], df_eval.loc[mask_coast, 'pred_position'],
            alpha=0.4, label='Coastal', color='blue', s=15)
plt.scatter(df_eval.loc[mask_river, target], df_eval.loc[mask_river, 'pred_position'],
            alpha=0.4, label='River/Estuary', color='green', s=15)

min_val = min(df_eval[target].min(), df_eval['pred_position'].min())
max_val = max(df_eval[target].max(), df_eval['pred_position'].max())
plt.plot([min_val, max_val], [min_val, max_val], 'r--', label='Perfect Prediction', linewidth=2)

plt.title("XGBoost: True vs Predicted Position (Transects NEVER seen during training)", fontsize=13)
plt.xlabel("True Shoreline Position (m)", fontsize=12)
plt.ylabel("AI-Predicted Position (m)", fontsize=12)
plt.legend()
plt.grid(True, linestyle=':', alpha=0.7)
plt.tight_layout()
plt.show()