import pandas as pd
import numpy as np
import json
import random
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from xgboost import XGBRegressor
import warnings
warnings.filterwarnings('ignore')

# --- CONFIGURATION ---
MODEL_DIR = 'models'
# Transect ID (e.g. 'Hoi_An_IA_TS_0015') or 'AUTO' for a random pick
# NOTE: only among transects NEVER SEEN during training (test set)
TRANSECT_ID = 'AUTO'

print("1. Loading models and test transects (never seen during training)...")
with open(f'{MODEL_DIR}/training_features.json', 'r') as f:
    training_features = json.load(f)

model_coast = XGBRegressor()
model_coast.load_model(f'{MODEL_DIR}/coast_model.json')
model_river = XGBRegressor()
model_river.load_model(f'{MODEL_DIR}/river_model.json')

# These CSVs contain ONLY transects that were never seen during training
# (generated by train_model.py via the segment_id group split)
df_coast_test = pd.read_csv(f'{MODEL_DIR}/test_coast.csv')
df_river_test = pd.read_csv(f'{MODEL_DIR}/test_river.csv')
df_clean = pd.concat([df_coast_test, df_river_test], ignore_index=True)

df_clean['date'] = pd.to_datetime(df_clean['date'])
df_clean = df_clean.sort_values(by=['segment_id', 'date'])
df_clean['site_name'] = df_clean['site_name'].astype('category')
df_clean['satellite'] = df_clean['satellite'].astype('category')

# Transect selection
if TRANSECT_ID == 'AUTO':
    counts = df_clean['segment_id'].value_counts()
    valid_transects = counts[counts >= 40].index.tolist()
    if not valid_transects:
        valid_transects = counts.index.tolist()
    TRANSECT_ID = random.choice(valid_transects)
    print(f"-> Randomly selected transect (never seen during training): {TRANSECT_ID}")
else:
    if TRANSECT_ID not in df_clean['segment_id'].unique():
        print(f"Warning: '{TRANSECT_ID}' is not in the test set (so it is either unknown, "
              f"or was seen during training -> result not reliable for evaluating generalization).")
    print(f"-> Analyzing transect: {TRANSECT_ID}")

df_t = df_clean[df_clean['segment_id'] == TRANSECT_ID].copy()
if df_t.empty:
    print(f"Error: No valid history found for {TRANSECT_ID} in the test set.")
    exit()

print("2. Generating AI mapping...")
is_river = df_t['in_river_zone'].iloc[0] == 1
model = model_river if is_river else model_coast

# The model predicts position in meters DIRECTLY
df_t['pred_position_m'] = model.predict(df_t[training_features])

print("3. Creating plot...")
plt.figure(figsize=(12, 6))

# Black line: ground truth
plt.plot(df_t['date'], df_t['cross_distance_m'],
         label='True Position (Satellite Observation)',
         color='black', marker='o', markersize=5, linewidth=2)

# Red line: AI prediction
plt.plot(df_t['date'], df_t['pred_position_m'],
         label='AI Prediction (Absolute Position)',
         color='red', linestyle='--', marker='x', markersize=5, linewidth=2)

# Plot styling
zone_type = "River/Estuary" if is_river else "Coast (Beach)"
plt.title(f"History vs AI Prediction - Transect NEVER SEEN: {TRANSECT_ID} ({zone_type})", fontsize=14)
plt.xlabel("Date", fontsize=12)
plt.ylabel("Absolute Shoreline Position (m)", fontsize=12)
plt.legend(fontsize=11, loc='best')
plt.grid(True, linestyle=':', alpha=0.7)

# Date axis formatting
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
plt.gca().xaxis.set_major_locator(mdates.MonthLocator(interval=6))
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()